name: Автоматическое комментирование на новых проблем

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Коментировать к новой проблеме
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Здравствуйте, спасибо что сообщили.
            Ниже приведены возможные таких проблем:

            # Не совместимость с 32-бит
            - Если у вас Операционная система установленна на 32-бит к сожалению проект предназначен на 64-бит.
            Мы понимаем и хотели бы также распространять проект к учащимся с 32 битными процессорами.
            К сожалению из-за новой версии Electron поэтому ничем ее сможем с этим поделать, в этом случае рекомендуется самим поменять версию и выполнить билд

            # Ошибка
            ## На случай если это ошибка, баг то выполните следующее:
            - Откройте терминал (не заходя в Администратора (sudo)) и выполните командой запуск к проекту
            - После этого будут логи проблемы,. Скопируйте их и отправьте сюда и ждите пока вам отвечут.

            На этом всё ожидайте последующие инструкции от коллабораторов. В-с-е-г-о х-о-р-о-ш-е-г-о!
