name: 🐛 Проблема
title: '[Проблема] '
description: Сообщить о проблеме
labels: ['type: проблема', 'status: нуждается в сортировке']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠️ Чеклист
      description: Перед созданием нового Issue, вы подтверждаете что выполнили следующие пункты
      options:
        - label: Я искал решение проблемы в [README](https://github.com/dvytvs/Ruscord-net-Linux/blob/main/README.md) и среди [Issues](https://github.com/dvytvs/Ruscord-net-Linux/issues)
        - label: Я скачал ``Ruscord.Net`` из [релизов официального репозитория](https://github.com/dvytvs/Ruscord-net-Linux/releases)

  - type: textarea
    id: description
    attributes:
      label: Опишите вашу проблему
      description: Чётко опишите проблему с которой вы столкнулись
      placeholder: Описание проблемы
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Версия Ruscord.Net
      description: Версия Ruscord.Net на которой вы получили проблему
      placeholder: Версия
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Шаги воспроизведения проблемы
      description: Шаги по воспроизведению поведения (вашей проблемы).
      placeholder: |
        Напишите здесь шаги, с помощью которых можно повторить вашу проблему
        на других компьютерах

  - type: textarea
    id: additions
    attributes:
      label: Дополнительные детали
      description: Дополнительные детали о которых нам нужно знать, к примеру логи из консоли
